version: '3.9'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    healthcheck:
      test: "curl http://localhost:8000"
      interval: 10s
      timeout: 5s
      retries: 5
